services:
  - docker

before_install:
  - docker build -t shred86/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shred86/react-test npm test

after_success:
  - docker build -t shred86/multi-client ./client
  - docker build -t shred86/multi-nginx ./nginx
  - docker build -t shred86/multi-server ./server
  - docker build -t shred86/multi-worker ./worker
  # Log into the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker hub
  - docker push shred86/multi-client
  - docker push shred86/multi-nginx
  - docker push shred86/multi-server
  - docker push shred86/multi-worker